kafka:
  name: kafka
  service:
    ports:
      tcp-kafka-int:
        port: 9092
        targetPort: 9092
      tcp-kafka-ctrl:
        port: 29093
        targetPort: 29093
  image:
    name: apache/kafka
    tag: 3.7.2
  resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1400Mi
  statefulset:
    replicas: 1
    revisionHistoryLimit: 5
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  secrets:
  env:
