{{ $config := .Values.kafka }}

{{ $imageConfig := $config.image }}

{{ $containerSecurityContext := fromYaml (.Files.Get "snippets/kafka/securityContext.yaml") }}

{{ $ctx := dict
  "name" $config.name
  "probe" $config.probe
  "statefulset" $config.statefulset
  "resources" $config.resources
  "containerSecurityContext" $containerSecurityContext
  "ports" $config.service.ports
  "envFrom" (list
    (include "template.configmap-env.name" $config.name)
  )
  "image" (include "template.image" (dict
    "name" $imageConfig.name
    "tag" $imageConfig.tag
  ))
}}

{{ include "template.statefulset" $ctx }}