version: '3.8'

services:
  app:
    image: ${REGISTRY}dbos-app:latest
    container_name: dbos-app
    build:
      context: app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/home/node/app
    environment:
      APP_DB_HOSTNAME: dbos-db
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: dbos-db
    image: ${REGISTRY}dbos-db:latest
    build:
      context: db
    shm_size: 128mb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "psql -c 'SELECT version()'"]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 1s
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}

volumes:
  db_data:
    driver: local
