version: '3.8'

services:
  app:
    container_name: dbos-app
    image: ${REGISTRY}dbos-app:latest
    restart: unless-stopped
    build:
      context: app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/home/node/app
    environment:
      TZ: ${TZ}
      APP_DB_HOSTNAME: dbos-db
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy

  db:
    container_name: dbos-db
    image: ${REGISTRY}dbos-db:latest
    build:
      context: docker/db
    ports:
      - '5435:5432'
    shm_size: 128mb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 1s
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}

  broker:
    container_name: dbos-app-broker
    image: ${REGISTRY}apache/kafka:latest
    user: root
    ports:
      - '9092:9092'
    environment:
      TZ: ${TZ}
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'd86da882-0c82-11ef-8bb9-a757193d3343'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka=WARN,kafka.controller=WARN,kafka.log.LogCleaner=WARN,state.change.logger=WARN,kafka.producer.async.DefaultEventHandler=WARN"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1"]
      interval: 2s
      timeout: 12s
      retries: 4
      start_period: 2s

  keycloak-db:
    container_name: dbos-app-keycloak-db
    image: ${REGISTRY}dbos-app-keycloak-db:latest
    build:
      context: docker/keycloak-db
    ports:
      - '5436:5432'
    shm_size: 128mb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 1s
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_DB_NAME: ${KC_DB}
      KEYCLOAK_DB_USER: ${KC_DB_USERNAME}
      KEYCLOAK_DB_PASSWORD: ${KC_DB_PASSWORD}

  keycloak:
    container_name: dbos-app-keycloak
    image: ${REGISTRY}dbos-app-keycloak:latest
    command: start-dev --import-realm --health-enabled=true
    build:
      context: docker/keycloak
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      TZ: ${TZ}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: "edge"
      KC_LOG_LEVEL: "ERROR"
    ports:
      - '9080:8080'
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import

  proxy:
    container_name: dbos-app-proxy
    image: ${REGISTRY}dbos-app-proxy:latest
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    command:
      - sh
      - -c
      - nginx-debug -g 'daemon off;'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: ${TZ}
    networks:
      default:
        aliases:
          - auth.dbosapp.test
          - app.dbosapp.test

  oauth2-proxy:
    container_name: dbos-app-oauth2-proxy
    image: ${REGISTRY}dbos-app-oauth2-proxy:latest
    build:
      context: docker/oauth2-proxy
      dockerfile: Dockerfile

    restart: unless-stopped
    ports:
      - 4180:4180/tcp
    environment:
      TZ: ${TZ}
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256

      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "keycloak oidc"
      OAUTH2_PROXY_CLIENT_ID: dbos-app

      OAUTH2_PROXY_REAL_CLIENT_IP_HEADER: "X-Forwarded-For"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_UPSTREAMS: "http://dbos-app:3000"

      OAUTH2_PROXY_CLIENT_SECRET: "72341b6d-7065-4518-a0e4-50ee15025608"
      OAUTH2_PROXY_REDIRECT_URL: http://app.dbosapp.test/oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://auth.dbosapp.test/realms/dbos-app
      OAUTH2_PROXY_REDEEM_URL: http://auth.dbosapp.test/realms/dbos-app/protocol/openid-connect/token
      OAUTH2_PROXY_REVERSE_PROXY: "true"

      OAUTH2_PROXY_WHITELIST_DOMAINS: ".dbosapp.test. app.dbosapp.test, auth.dbosapp.test"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_WEBSOCKETS: "true"

      OAUTH2_PROXY_COOKIE_SECRET: "OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_REFRESH: 1m30s
      OAUTH2_PROXY_COOKIE_SAMESITE: "strict"
      OAUTH2_PROXY_COOKIE_DOMAINS: ".dbosapp.test"
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"

      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"

      OAUTH2_PROXY_REQUEST_LOGGING: "false"
      OAUTH2_PROXY_AUTH_LOGGING: "false"
      # OAUTH2_PROXY_SCOPE: 'email'

    depends_on:
      - proxy
      - app
      - keycloak

volumes:
  kafka_data:
    driver: local
  db_data:
    driver: local
  keycloak_db_data:
    driver: local
