{{ $ctx := dict
  "name" .Values.db.name
  "registry" .Values.registry
  "deployment" .Values.db.deployment
  "service" .Values.db.service
  "release" .Release
  "chart" .Chart
  "volumeMountPath" "/var/lib/postgresql"
}}

{{ include "dbos-app.dpl" $ctx }}
