apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbos-db

spec:
  selector:
    matchLabels:
      service: dbos-db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        service: dbos-db
    spec:
      volumes:
        - name: dbos-db-data
          persistentVolumeClaim:
            claimName: dbos-db-data-pvc
      containers:
        - name: dbos-db
          image: "localhost:32000/dbos-db:latest"
          volumeMounts:
            - name: dbos-db-data
              mountPath: /var/lib/postgresql
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: db-secrets
            - secretRef:
                name: app-db-secrets
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "4G"
              cpu: 2
          ports:
            - containerPort: 5432

          imagePullPolicy: Always
      restartPolicy: Always

status: {}


