# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-sdk/main/dbos-config.schema.json

database:
  hostname: ${APP_DB_HOSTNAME}
  username: ${APP_DB_USER}
  password: ${APP_DB_PASSWORD}
  port: 5432
  app_db_name: ${APP_DB_NAME}
  connectionTimeoutMillis: 3000
  app_db_client: knex
  ssl: false
  migrate:
    - npx knex migrate:latest
  rollback:
    - npx knex migrate:rollback

runtimeConfig:
  port: 3000 # Optional, defaults to 3000

env:
  brokers: ${BROKERS}