FROM node:22-bookworm-slim
# We use root user for dev images to allow for despace whichs runs as root
# include some dev tools
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    net-tools \
    dnsutils \
    htop \
    mc \
    vim \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g typescript tsx nodemon

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

ENV NODE_ENV=development
COPY package*.json ./
RUN npm ci
RUN npm install typescript@5.5.2 @types/node

COPY tsconfig.json ./
COPY nodemon.json ./
COPY dbos-config.yaml ./
COPY start_dev.sh ./

COPY start_dev.sh ./
RUN chmod +x start_dev.sh
ENV NODE_ENV=development


ENTRYPOINT [ "/home/node/app/start_dev.sh" ]
EXPOSE 3000