{{ $config := .Values.keycloak }}

{{ $keycloakHeadlessServiceName := include "template.service.name" (printf "%s-headless" $config.name) }}

{{ $keycloakServiceName := include "template.service.name" $config.name }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $keycloakHeadlessServiceName }}
spec:
  clusterIP: None
  selector:
    service: {{ $keycloakServiceName }}
