keycloak:
  name: app-keycloak
  deployment:
    image:
      name: app-keycloak
      version: latest
    revisionHistoryLimit: 5
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    resources:
      requests:
        java: 512m
        memory: 512Mi
        cpu: 1
      limits:
        java: 1024m
        memory: 1Gi
        cpu: 1
    probe:
      method:
        httpGet:
          path: /health/ready
          port: 9000
      liveness:
        initialDelaySeconds: 5
        periodSeconds: 15
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readiness:
        initialDelaySeconds: 5
        periodSeconds: 30
        timeoutSeconds: 5
        successThreshold: 1
  service:
    port: 8080
    targetPort: 8080
    ingress:
      className: nginx
      host: auth.dbosapp.test
  secrets:
    KEYCLOAK_ADMIN: "admin"
    KEYCLOAK_ADMIN_PASSWORD: "admin"
    KC_DB_USERNAME: "keycloak"
    KC_DB_PASSWORD: "keycloak"
  env:
    KC_DB_URL_DATABASE: "keycloak"
