{{ $config := .Values.keycloak }}
{{ $domain := .Values.domain }}
{{ $resourcesSettings := $config.resources }}

{{ $keycloakHeadlessServiceName := include "template.service.name" (printf "%s-headless" $config.name) }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.configmap-env.name" $config.name }}
data:
  KC_DB: postgres
  KC_DB_SCHEMA: public
  KC_DB_URL_DATABASE: {{ $config.env.KC_DB_URL_DATABASE }}
  KC_DB_URL_HOST: {{ include "template.service.name" .Values.keycloak_db.name }}
  KC_DB_URL_PORT: "5432"
  KC_HOSTNAME: {{ printf "auth.%s" .Values.domain }}
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY_HEADERS: forwarded
  KC_CACHE: ispn
  KC_CACHE_STACK: kubernetes
  JAVA_OPTS_APPEND: {{ printf "-Xms%s -Xmx%s -Djgroups.dns.query=%s" $resourcesSettings.requests.java  $resourcesSettings.limits.java $keycloakHeadlessServiceName}}

