{{ $config := .Values.keycloak }}
{{ $serviceName := include "template.service.name" (dict "name" $config.name) }}

{{ $rootPath := dict
  "path" $config.hosts.base.paths.root
  "backend" (dict
    "service" $serviceName
    "port" (dict
      "number" $config.service.ports.keycloak.port
    )
  )
}}

{{ $ctx := dict
  "host" (printf "auth.%s" .Values.domain)
  "name" "keycloak"
  "paths" (list $rootPath)
}}

{{ include "template.ingress" $ctx }}