{{ $config := .Values.keycloak }}

{{ $keycloakHeadlessCtx := dict
  "name" (printf "%s-headless" $config.name)
  "release" .Release
}}
{{ $keycloakHeadlessServiceName := include "template.svc.name" $keycloakHeadlessCtx }}

{{ $ctx := dict
  "name" $config.name
  "release" .Release
}}

{{ $keycloakServiceName := include "template.svc.name" $ctx }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $keycloakHeadlessServiceName }}
spec:
  clusterIP: None
  selector:
    service: {{ $keycloakServiceName }}
