{{ $ctx := dict
  "name" .Values.keycloak.name
  "release" .Release
  "chart" .Chart
}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dbos-app.configmap.name" $ctx }}
data:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KC_DB: "postgres"
  KC_DB_SCHEMA: "public"
  KC_DB_USERNAME: "keycloak"
  KC_DB_PASSWORD: "keycloak"
  KC_DB_URL_HOST: "keycloak-db"
  KC_DB_URL_PORT: "5432"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_PROXY: "edge"
  KC_LOG_LEVEL: "ERROR"
