{{ $config := .Values.keycloak }}

{{ $ctx := dict
  "name" $config.name
  "registry" .Values.registry
  "deployment" $config.deployment
  "service" $config.service
  "release" .Release
}}

{{ include "template.dpl" $ctx }}