{{ $ctx := dict
  "name" .Values.keycloak.name
  "registry" .Values.registry
  "deployment" .Values.keycloak.deployment
  "service" .Values.keycloak.service
  "release" .Release
  "chart" .Chart
}}

{{ include "template.dpl" $ctx }}
