{{ $config := .Values.keycloak }}

{{ $serviceName := include "template.service.name" (printf "%s-headless" $config.name) }}

{{ $selectorService := include "template.service.name" $config.name }}

{{ $ctx := dict
    "clusterIP" "None"
    "serviceName" $serviceName
    "selectorService" $selectorService
}}

{{ include "template.service" $ctx }}