{{- define "template.deployment"}}
{{ $deploymentName := include "template.deployment.name" .name }}

{{ $serviceName := .serviceName }}
{{ $volumes := .volumes }}

{{ if not $serviceName }}
  {{ $serviceName = include "template.service.name" .name }}
{{ end }}

{{ $containerCtx := dict
    "name" $serviceName
    "probe" .probe
    "image" .image
    "ports" .ports
    "resources" .resources
    "volumeMounts" .volumeMounts
    "envFrom" .envFrom
    "secretsFrom" .secretsFrom
    "securityContext" .containersecurityContext
}}

{{ $container := include "template.container" $containerCtx }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
spec:
  replicas: {{ .deployment.replicas }}
  selector:
    matchLabels:
      service: {{ $serviceName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .deployment.rollingUpdate.maxUnavailable }}
  revisionHistoryLimit: {{ .deployment.revisionHistoryLimit }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: {{ $serviceName }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            service:  {{ $serviceName }}
      securityContext:
        sysctls:
          - name: "net.ipv4.ip_unprivileged_port_start"
            value: "0"
      {{- if $volumes }}
      volumes:
      {{- range $volumes }}
        -
{{ toYaml . | indent 10 -}}
      {{ end }}
      {{- end }}
      containers:
{{ $container | indent 8 }}
status: {}
{{ end -}}