{{- define "dbos-app.ingress"}}
{{ $ingressSettings := .service.ingress }}
apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: {{ include "dbos-app.ingress.name" . }}
{{- include "dbos-app.labels" . | indent 2 }}
spec:
  ingressClassName: {{ $ingressSettings.className | quote }}
  rules:
    - host: {{ $ingressSettings.host }}
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: {{ include "dbos-app.svc.name" . }}
                port:
                  number: {{ .service.port }}
{{ end -}}

