{{- define "template.labels.list" }}
heritage: {{ .release.Service | quote }}
release: {{ .release.Name | quote }}
app: {{ include "template.fullname" . | quote}}
{{ end -}}

{{- define "template.labels" }}
labels:
{{- include "template.labels.list" . | indent 2 -}}
{{ end -}}
