{{- define "template.dpl.name"}}
{{- printf "%s-%s-dpl" .release.Name .name -}}
{{ end -}}

{{- define "template.svc.name"}}
{{- printf "%s-%s-svc" .release.Name .name -}}
{{ end -}}

{{- define "template.pv.name"}}
{{- printf "%s-%s-pv" .release.Name .name -}}
{{ end -}}

{{- define "template.pvc.name"}}
{{- printf "%s-%s-pvc" .release.Name .name -}}
{{ end -}}

{{- define "template.secrets.name"}}
{{- printf "%s-%s-secrets" .release.Name .name -}}
{{ end -}}

{{- define "template.ingress.name"}}
{{- printf "%s-%s-ingress" .release.Name .name -}}
{{ end -}}

{{- define "template.configmap.name"}}
{{- printf "%s-%s-configmap" .release.Name .name -}}
{{ end -}}
