{{- define "template.deployment.name"}}
{{- printf "%s-dpl" .name -}}
{{ end -}}

{{- define "template.service.name"}}
{{- printf "%s-svc" .name -}}
{{ end -}}

{{- define "template.pv.name"}}
{{- printf "%s-pv" .name -}}
{{ end -}}

{{- define "template.pvc.name"}}
{{- printf "%s-pvc" .name -}}
{{ end -}}

{{- define "template.secrets.name"}}
{{- printf "%s-secrets" .name -}}
{{ end -}}

{{- define "template.ingress.name"}}
{{- printf "%s-ingress" .name -}}
{{ end -}}

{{- define "template.configmap.name"}}
{{- printf "%s-configmap" .name -}}
{{ end -}}
