{{- define "template.pv"}}
apiVersion: v1

kind: PersistentVolume

metadata:
  name: {{ include "template.pv.name" . }}
  labels:
    type: local
{{- include "template.labels.list" . | indent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .volume.storage | quote }}
  accessModes:
    - {{ .volume.accessMode | quote }}
  hostPath:
    path: {{ .volume.hostPath | quote }}
{{ end -}}
