{{- define "template.pvc"}}
apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: {{ include "template.pvc.name" . }}
spec:
  storageClassName: manual
  accessModes:
    - {{ .volumeClaim.accessMode | quote }}
  volumeName: {{ include "template.pv.name" . }}
  resources:
    requests:
        storage: {{ .volumeClaim.storage }}
{{ end -}}

