{{- define "template.secrets"}}
apiVersion: v1

kind: Secret

metadata:
  name: {{ include "template.secrets.name" . }}
type: Opaque
data:
{{- range $k, $v := .secrets }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{ end -}}
