{{- define "dbos-app.secrets"}}
apiVersion: v1

kind: Secret

metadata:
  name: {{ include "dbos-app.secrets.name" . }}
{{- include "dbos-app.labels" . | indent 2 }}
type: Opaque
data:
{{- range $k, $v := .secrets }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{ end -}}
