{{- define "template.service" }}

{{ $name := .name }}
{{ $namespace := .namespace }}
{{ $type := .type }}
{{ $serviceName := .serviceName }}
{{ $clusterIP := .clusterIP }}

{{ $ports := .ports }}

{{- if not $serviceName }}
  {{ $serviceName = include "template.service.name" $name }}
{{- end }}

{{ $selectorService := $serviceName }}
{{ if .selectorService }}
  {{ $selectorService = .selectorService }}
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  {{- if $namespace }}
  namespace: {{ $namespace }}
  {{- end }}
  labels:
    service: {{ $selectorService }}
spec:
  {{- if $type }}
  type: {{ $type }}
  {{- end }}
  {{- if $clusterIP }}
  clusterIP: {{ $clusterIP }}
  {{- end }}
  {{- if $ports }}
  ports:
    {{- range  $k, $v := $ports }}
    - name: {{ $k | kebabcase }}
      port: {{ $v.port }}
      targetPort: {{ $v.targetPort }}
      protocol: {{ $v.protocol | default "TCP"}}
      {{- if $v.nodePort }}
      nodePort: {{ $v.nodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector:
    service: {{ $selectorService }}
{{ end -}}