{{- define "template.service" }}

{{ $name := .name }}
{{ $serviceName := .serviceName }}
{{ $ports := .ports }}

{{- if not $serviceName }}
  {{ $serviceName = include "template.service.name" $name }}
{{- end }}

{{ $selectorService := $serviceName }}
{{ if .selectorService }}
  {{ $selectorService = .selectorService }}
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    service: {{ $selectorService }}
spec:
  ports:
    {{- range  $k, $v := $ports }}
    - name: {{ $k | kebabcase }}
      port: {{ $v.port }}
      targetPort: {{ $v.targetPort }}
      protocol: {{ $v.protocol | default "TCP"}}
    {{- end }}
  selector:
    service: {{ $selectorService }}
{{ end -}}