{{- define "template.svc"}}
{{ $serviceName := include "template.svc.name" . }}

apiVersion: v1

kind: Service

metadata:
  name: {{ $serviceName }}
  labels:
    service: {{ $serviceName }}
{{- include "template.labels.list" . | indent 4 }}
spec:
  ports:
    {{- range .ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    service: {{ $serviceName | quote }}
{{ end -}}
