apiVersion: v1

kind: PersistentVolume

metadata:
  name: {{ $.Release.Name }}-home
  labels:
    type: local

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: {{ .Values.dev.homeDir}}/{{ $.Release.Name }}-home
