{{ $ctx := dict
  "name" .Values.app.name
  "registry" .Values.registry
  "deployment" .Values.app.deployment
  "service" .Values.app.service
  "release" .Release
  "chart" .Chart
  "volumeMountPath" "/home/node/app"
}}

{{ include "dbos-app.dpl" $ctx }}
