apiVersion: v1
kind: Service
metadata:
  name: dbos-app
  namespace: {{ .Values.namespace }}
  labels:
    service: dbos-app

spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    service: dbos-app
