{{ $ctx := dict
  "name" .Values.app.name
  "release" .Release
  "chart" .Chart
}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dbos-app.configmap.name" $ctx }}
data:
  APP_DB_HOSTNAME: dbos-db-svc