{{ $qServiceName := printf "%s-%s-svc" .Release.Name "app" }}
{{ $ctx := dict
  "name" .Values.app.name
  "service" .Values.app.service
  "release" .Release
  "chart" .Chart
}}

apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ $qServiceName }}
{{- include "dbos-app.labels" $ctx | indent 2 }}

spec:
  selector:
    matchLabels:
      service: {{ $qServiceName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        service: {{ $qServiceName }}
    spec:
      volumes:
        - name: {{ $qServiceName }}
          persistentVolumeClaim:
            claimName: {{ include "dbos-app.pvc.name" $ctx }}
      containers:
        - name: {{ $qServiceName }}
          image: {{ .Values.registry }}/{{ .Values.images.app }}
          volumeMounts:
            - name: {{ $qServiceName }}
              mountPath: /home/node/app
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "4Gi"
              cpu: 2
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 1
            timeoutSeconds: 3
            httpGet:
              path: /
              port: {{ $ctx.service.port }}
              scheme: HTTP
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 3
            httpGet:
              path: /
              port: {{ $ctx.service.port }}
              scheme: HTTP
          ports:
            - containerPort: {{ $ctx.service.port }}
          imagePullPolicy: Always
      restartPolicy: Always
status: {}
