keycloak_db:
  name: app-keycloak-db
  service:
    ports:
      keycloak_db:
        port: 5432
        targetPort: 5432
  image:
    name: app-keycloak-db
    version: latest
  probe:
    method:
      exec:
        command: ["sh", "-c", "pg_isready"]
    liveness:
      initialDelaySeconds: 10
      successThreshold: 1
      failureThreshold: 3
      periodSeconds: 3
      timeoutSeconds: 12
    readiness:
      initialDelaySeconds: 1
      successThreshold: 1
      failureThreshold: 3
      periodSeconds: 1
      timeoutSeconds: 3

  deployment:
    revisionHistoryLimit: 5
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 1Gi
        cpu: 1
  volume:
    hostPath: ""
    storage: 1Gi
    accessMode: ReadWriteOnce
  secrets:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    KEYCLOAK_DB_NAME: keycloak
    KEYCLOAK_DB_USER: keycloak
    KEYCLOAK_DB_PASSWORD: keycloak
