{{ $config := .Values.keycloak_db }}
{{ $imageConfig := $config.image }}

{{ $namesCtx := dict
  "name" $config.name
}}

{{ $persistentVolumeName := include "template.pv.name" $namesCtx }}
{{ $pvcName := include "template.pvc.name" $namesCtx }}

{{ $persistentVolume := (dict
  "name" $persistentVolumeName
  "persistentVolumeClaim" (dict "claimName" $pvcName)
  )
}}

{{ $persistentVolumeMount := (dict
  "name" $persistentVolumeName
  "mountPath" "/var/lib/postgresql"
)}}

{{ $ctx := dict
  "name" $config.name
  "probe" $config.probe
  "deployment" $config.deployment
  "ports" $config.service.ports
  "envFrom" (list
    (include "template.configmap.name" (dict "name" $config.name))
  )
  "secretsFrom" (list
    (include "template.secrets.name" (dict "name" $config.name))
  )
  "image" (include "template.image" (dict
    "registry" .Values.registry
    "name" $imageConfig.name
    "tag" $imageConfig.tag
  ))
  "volumes" (list $persistentVolume)
  "volumeMounts" (list $persistentVolumeMount)
}}

{{ include "template.deployment" $ctx }}