{{ $config := .Values.keycloak_db }}

{{ $namesCtx := dict
  "name" $config.name
  "release" .Release
}}

{{ $persistentVolumeName := include "template.pv.name" $namesCtx }}
{{ $pvcName := include "template.pvc.name" $namesCtx }}

{{ $persistentVolume := (dict
  "name" $persistentVolumeName
  "persistentVolumeClaim" (dict "claimName" $pvcName)
  )
}}

{{ $persistentVolumeMount := (dict
  "name" $persistentVolumeName
  "mountPath" "/var/lib/postgresql"
)}}

{{ $ctx := dict
  "name" $config.name
  "registry" .Values.registry
  "deployment" $config.deployment
  "service" $config.service
  "release" .Release
}}

{{ include "template.dpl" $ctx }}
