{{
  $servicePort := dict
    "name" "keycloak-db-port"
    "port" .Values.keycloak_db.service.port
    "targetPort" .Values.keycloak_db.service.targetPort
}}
{{ $ports := list $servicePort }}

{{ $ctx := dict
  "name" .Values.keycloak_db.name
  "service" .Values.keycloak_db.service
  "ports" $ports
  "release" .Release
}}

{{ include "template.svc" $ctx }}
