nginx_controller:
  name: nginx-controller
  namespace: nginx-controller
  source:
    targetRevision: 4.11.3
  values:
    fullnameOverride: nginx
    controller:
      allowSnippetAnnotations: true
      config:
        default-type: application/octet-stream
        ignore-invalid-headers: on
        upstream-keepalive-timeout:  65
        client-header-timeout: 240
        client-body-timeout: 240
        client-body-buffer-size: 2m
        client-header-buffer-size: 10k
        large-client-header-buffers: 8 1024k
        proxy-body-size: 100m
        proxy-send-timeout: 240
        proxy-buffer-size: 128k
        proxy-buffers-number: 8
        proxy-busy-buffers-size: 256k
