apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cr-pvc
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
