{{ $config := .Values.backend_oauth2_proxy }}
{{ $secrets := $config.secrets }}

{{ $ctx := dict
  "name" $config.name
  "secrets" (dict
    "OAUTH2_PROXY_CLIENT_ID"  "app"
    "OAUTH2_PROXY_CLIENT_SECRET" "72341b6d-7065-4518-a0e4-50ee15025608"
    "OAUTH2_PROXY_COOKIE_SECRET" "OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
  )
}}
{{ include "template.secrets" $ctx }}

