{{ $config := .Values.backend }}
{{ $secrets := $config.secrets }}

{{ $ctx := dict
  "name" $config.name
  "secrets" (dict
    "OAUTH2_PROXY_CLIENT_ID"  .Values.empower_backend.secrets.EMPOWER_CLIENT_ID
    "OAUTH2_PROXY_CLIENT_SECRET" .Values.empower_backend.secrets.EMPOWER_CLIENT_SECRET
    "OAUTH2_PROXY_COOKIE_SECRET" $secrets.OAUTH2_PROXY_COOKIE_SECRET
  )
}}
{{ include "template.secrets" $ctx }}

