{{ $config := .Values.backend_oauth2_proxy }}
{{ $imageConfig := $config.image }}

{{ $ctx := dict
  "name" $config.name
  "deployment" $config.deployment
  "resources" $config.resources
  "service" $config.service
  "envFrom" (list
    (include "template.configmap-env.name" $config.name)
  )
  "secretsFrom" (list
    (include "template.secrets.name" $config.name)
  )
  "image" (include "template.image" (dict
    "name" $imageConfig.name
    "tag" $imageConfig.tag
  ))

}}

{{ include "template.deployment" $ctx }}