{{ $config := .Values.backend_oauth2_proxy }}
{{ $serviceName := include "template.service.name" $config.name }}

{{ $rootPath := dict
  "path" $config.hosts.base.paths.root
  "backend" (dict
    "service" $serviceName
    "port" (dict
      "number" $config.service.ports.oauth2proxy.port
    )
  )
}}

{{ $ctx := dict
  "host" (printf "oauth2.%s" .Values.domain)
  "name" "oauth2"
  "paths" (list $rootPath)
}}


{{ include "template.ingress" $ctx }}