
{{ $config := .Values.nginx_controller }}
{{ $namespace := $config.namespace | default "default"}}
{{ $serviceName := $config.values.fullnameOverride }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  hosts.override: |
    rewrite name auth.{{ .Values.domain }} {{ $serviceName }}-controller.{{ $namespace }}.svc.cluster.local
