{{- define "dbos-app.svc"}}
{{ $serviceName := include "dbos-app.svc.name" . }}

apiVersion: v1

kind: Service

metadata:
  name: {{ $serviceName | quote }}
  labels:
    service: {{ $serviceName }}
{{- include "dbos-app.labels.list" . | indent 4 }}
spec:
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.targetPort }}
  selector:
    service: {{ $serviceName | quote }}
{{ end -}}
