apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbos-db
spec:
  selector:
    matchLabels:
      service: dbos-db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        service: dbos-db
    spec:
      volumes:
        - name: dbos-db-data
          persistentVolumeClaim:
            claimName: dbos-db-data-pvc
      containers:
        - name: dbos-db
          image: "localhost:32000/dbos-db:latest"
          volumeMounts:
            - name: dbos-db-data
              mountPath: /var/lib/postgresql
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secrets
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "4G"
              cpu: 2
          ports:
            - containerPort: 5432
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /
          #     port: 3000
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 10
          #   initialDelaySeconds: 60
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /
          #     port: 3000
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 10
          #   initialDelaySeconds: 60
          imagePullPolicy: Always
      restartPolicy: Always

status: {}


