apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbos-home
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/tmp/dbos-home"
