{{- $secrets := mustMergeOverwrite (dict) .Values.backend_db.secrets .Values.backend.secrets -}}

{{ $ctx := dict
  "name" .Values.backend_db.name
  "secrets" $secrets
  "release" .Release
}}

{{ include "template.secrets" $ctx }}
