registry: localhost:32000

app:
  name: app
  deployment:
    image:
      name: dbos-app
      version: latest
    revisionHistoryLimit: 5
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2
    probe:
      method:
        httpGet:
          path: /
          port: 3000
          scheme: HTTP
      liveness:
        initialDelaySeconds: 10
        successThreshold: 1
        failureThreshold: 3
        periodSeconds: 3
        timeoutSeconds: 12
      readiness:
        initialDelaySeconds: 1
        successThreshold: 1
        failureThreshold: 3
        periodSeconds: 1
        timeoutSeconds: 3
  service:
    port: 3000
    targetPort: 3000
    ingress:
      className: nginx
      host: dbos
  volume:
    hostPath: ""
    storage: 1Gi
    accessMode: ReadOnlyMany
  secrets:
    APP_DB_NAME: app
    APP_DB_USER: app
    APP_DB_PASSWORD: app

db:
  name: db
  service:
    port: 5432
    targetPort: 5432
  deployment:
    image:
      name: dbos-db
      version: latest
    revisionHistoryLimit: 5
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 1Gi
        cpu: 1
    probe:
      method:
        exec:
          command: ["sh", "-c", "pg_isready"]
      liveness:
        initialDelaySeconds: 10
        successThreshold: 1
        failureThreshold: 3
        periodSeconds: 3
        timeoutSeconds: 12
      readiness:
        initialDelaySeconds: 1
        successThreshold: 1
        failureThreshold: 3
        periodSeconds: 1
        timeoutSeconds: 3
  volume:
    hostPath: ""
    storage: 1Gi
    accessMode: ReadWriteOnce
  secrets:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
