registry: localhost:32000

images:
  db: dbos-db:latest
  app: dbos-app:latest

ingress:
  className: nginx
  hosts:
    - host: dbos
      paths:
        - path: /
          pathType: Prefix
          service: app
          port: 3000

app:
  name: app
  service:
    port: 3000
    targetPort: 3000
  volume:
    storage: 1Gi
    accessMode: ReadOnlyMany
  volumeClaim:
    storage: 1Gi
    accessMode: ReadOnlyMany
  secrets:
    APP_DB_NAME: app
    APP_DB_USER: app
    APP_DB_PASSWORD: app

db:
  name: db
  service:
    port: 5432
    targetPort: 5432
  volume:
    storage: 10Gi
    accessMode: ReadWriteOnce
  volumeClaim:
    storage: 1Gi
    accessMode: ReadWriteOnce
  secrets:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

dev:
  appDir: "/home/demetris/projects/dbos-docker-tpl/app"
  homeDir: "/tmp/"

secrets:
  db:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  app:
    APP_DB_NAME: app
    APP_DB_USER: app
    APP_DB_PASSWORD: app