backend:
  name: app-backend
  hosts:
    base:
      paths:
        root:
          path: /
          pathType: Prefix
  image:
    name: app-backend
    version: latest

  probe:
    method:
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
    liveness:
      initialDelaySeconds: 10
      successThreshold: 1
      failureThreshold: 3
      periodSeconds: 3
      timeoutSeconds: 12
    readiness:
      initialDelaySeconds: 1
      successThreshold: 1
      failureThreshold: 3
      periodSeconds: 1
      timeoutSeconds: 3
  resources:
    requests:
      memory: "1Gi"
      cpu: 1
    limits:
      memory: "2Gi"
      cpu: 2

  deployment:
    revisionHistoryLimit: 5
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  service:
    ports:
      backend:
        name: backend
        port: 3000
        targetPort: 3000
  volume:
    hostPath: ""
    storage: 1Gi
    accessMode: ReadOnlyMany
  env:
    brokers: 'kafka-svc.dbos.svc.cluster.local:9092'
  secrets:
    APP_DB_NAME: app
    APP_DB_USER: app
    APP_DB_PASSWORD: app
