
{{ $config := .Values.backend }}
{{ $namesCtx := dict
  "name" $config.name
  "release" .Release
}}

{{ $persistentVolumeName := include "template.pv.name" $namesCtx }}
{{ $pvcName := include "template.pvc.name" $namesCtx }}

{{ $persistentVolume := (dict
  "name" $persistentVolumeName
  "persistentVolumeClaim" (dict "claimName" $pvcName)
  )
}}

{{ $persistentVolumeMount := (dict
  "name" $persistentVolumeName
  "mountPath" "/home/node/app"
)}}

{{ $ctx := dict
  "name" $config.name
  "registry" .Values.registry
  "deployment" $config.deployment
  "service" $config.service
  "volumes" (list $persistentVolume )
  "volumeMounts" (list $persistentVolumeMount )
  "release" .Release
}}

{{ include "template.dpl" $ctx }}
