{{ $ctx := dict
  "name" .Values.backend.name
}}

{{ $dbctx := dict
  "name" .Values.backend_db.name
}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.configmap-env.name" $ctx }}
data:
  APP_DB_HOSTNAME: {{ include "template.service.name" $dbctx }}
  BROKERS: {{ .Values.backend.config.brokers }}