
{{ $config := .Values.backend }}
{{ $imageConfig := $config.image }}

{{ $ctx := dict
  "name" $config.name
  "probe" $config.probe
  "resources" $config.deployment.resources
  "ports" $config.service.ports
  "envFrom" (list
    (include "template.configmap.name" (dict "name" $config.name))
  )
  "secretsFrom" (list
    (include "template.secrets.name" (dict "name" $config.name))
  )
  "image" (include "template.image" (dict
    "registry" .Values.registry
    "name" $imageConfig.name
    "tag" $imageConfig.tag
  ))
}}

{{ include "template.deployment" $ctx }}