{{ $config := .Values.backend }}
{{ $serviceName := include "template.service.name" $config.name }}

{{ $rootPath := dict
  "path" $config.hosts.base.paths.root
  "backend" (dict
    "service" $serviceName
    "port" (dict
      "number" $config.service.ports.backend.port
    )
  )
}}

{{ $ctx := dict
  "host" (printf "api.%s" .Values.domain)
  "name" "api"
  "paths" (list $rootPath)
}}

{{ include "template.ingress" $ctx }}