#!/bin/bash
set -e
echo $KEYCLOAK_DB_NAME
echo $KEYCLOAK_DB_USER
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $KEYCLOAK_DB_USER PASSWORD '$KEYCLOAK_DB_PASSWORD' NOSUPERUSER CREATEDB;
	CREATE DATABASE $KEYCLOAK_DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB_NAME TO $KEYCLOAK_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$KEYCLOAK_DB_NAME" <<-EOSQL
	GRANT ALL PRIVILEGES ON SCHEMA public TO $KEYCLOAK_DB_USER;
EOSQL

