registry: localhost:32000

backend:
  name: dbos-backend
  image:
    name: dbos-backend
    version: latest

backend_db:
  name: dbos-backend-db
  image:
    name: dbos-backend-db
    version: latest
  volume:
    hostPath: "/tmp/dbos-app/db"

keycloak:
  name: dbos-keycloak
  image:
    name: dbos-keycloak
    version: latest

keycloak_db:
  name: dbos-keycloak-db
  image:
    name: dbos-keycloak-db
    version: latest
  volume:
    hostPath: "/tmp/dbos-app/keycloak-db"