namespace: dbos-app

registry:
  url: localhost:32000

images:
  db: dbos-db:latest
  app: dbos-app:latest

ingress:
  name: "dbos-app-ingress"
  className: "nginx"
  hosts:
    - host: dbos
      paths:
        - path: /
          pathType: Prefix
          service: dbos-app
          port: 3001
  tls: []


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}


secrets:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  APP_DB_USER: app
  APP_DB_NAME: app
  APP_DB_PASSWORD: app